FROM ubuntu:24.04
WORKDIR /root
LABEL org.opencontainers.image.authors="zzx"
SHELL ["/bin/bash", "-c"]

ENV DEBIAN_FRONTEND=noninteractive

# universe is enabled by default in the ubuntu:24.04 image, so no add-apt-repository needed
RUN apt-get update

# SETUP THE AFNI
# install prerequisite packages
RUN apt-get install -y tcsh xfonts-base libssl-dev       \
python-is-python3                 \
python3-matplotlib python3-numpy  \
python3-flask python3-flask-cors  \
python3-pil                       \
gsl-bin netpbm gnome-tweaks       \
libjpeg62 xvfb xterm vim curl     \
gedit evince eog                  \
libglu1-mesa-dev libglw1-mesa-dev \
libxm4 build-essential            \
libcurl4-openssl-dev libxml2-dev  \
libgfortran-14-dev libgomp1       \
gnome-terminal nautilus           \
firefox xfonts-100dpi             \
r-base-dev cmake bc               \
libgdal-dev libopenblas-dev       \
libnode-dev libudunits2-dev

# Install AFNI binaries
RUN cd
RUN curl -O https://afni.nimh.nih.gov/pub/dist/bin/misc/@update.afni.binaries
RUN tcsh @update.afni.binaries -package linux_ubuntu_24_ARM -do_extras
RUN echo  'export PATH=$HOME/abin/:$PATH' >> ~/.bashrc
RUN echo  'export PATH=$HOME/abin/:$PATH' >> ~/.cshrc

# Install R
RUN export R_LIBS=$HOME/R && mkdir $R_LIBS
RUN echo  'export R_LIBS=$HOME/R' >> ~/.bashrc
RUN echo  'setenv R_LIBS ~/R'     >> ~/.cshrc

ENV PATH="/root/abin/:$PATH"
ENV R_LIBS="/root/R"

# Update R to a newer version using the official CRAN repo for Ubuntu 24.04 (noble).
# IMPORTANT: do this BEFORE installing any R packages, otherwise packages built
# against the old Ubuntu R (4.3.3) become stale/broken after the upgrade.
# (apt-key adv is deprecated/unreliable on 24.04; use CRAN's official key instead)
RUN curl -fsSL https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc
RUN echo 'deb https://cloud.r-project.org/bin/linux/ubuntu noble-cran40/' > /etc/apt/sources.list.d/cran.list
RUN apt-get update
RUN apt-get install -y r-base-dev && R --version | head -1

# To avoid failure in installing R packages, we use a modified version of rPkgsInstall
# in which we changed the tolerance for timeout failure.
COPY rPkgsInstall.R /root/abin/rPkgsInstall.R
RUN rPkgsInstall -pkgs ALL

# nicefy terminal
RUN echo 'set filec'    >> ~/.cshrc
RUN echo 'set autolist' >> ~/.cshrc
RUN echo 'set nobeep'   >> ~/.cshrc

RUN echo 'alias ls ls --color=auto' >> ~/.cshrc
RUN echo 'alias ll ls --color -l'   >> ~/.cshrc
RUN echo 'alias ltr ls --color -ltr'   >> ~/.cshrc
RUN echo 'alias ls="ls --color"'    >> ~/.bashrc
RUN echo 'alias ll="ls --color -l"' >> ~/.bashrc
RUN echo 'alias ltr="ls --color -ltr"' >> ~/.bashrc

# install extras
RUN @afni_R_package_install -shiny -circos

# Extra fix
RUN cp /root/abin//AFNI.afnirc ~/.afnirc
RUN suma -update_env
RUN apsearch -update_all_afni_help

RUN apt-get install -y sshfs